name: Daily Order Emailer

on:
  schedule:
    - cron: '0 13 * * *'  # 9am EST (13:00 UTC)
  workflow_dispatch:      # Allow manual trigger

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run email script
        env:
          SHOPIFY_STORE_NAME: ${{ secrets.SHOPIFY_STORE_NAME }}
          SHOPIFY_API_VERSION: ${{ secrets.SHOPIFY_API_VERSION }}
          SHOPIFY_ADMIN_API_TOKEN: ${{ secrets.SHOPIFY_ADMIN_API_TOKEN }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python order_emailer.py
